FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# run cmd
RUN npm install

# copy จาก ผู้ใช้ทางฝั่งซ้าย ไปยังฝั่งขวาคือ server
COPY . .

# localhost vite post 5173
EXPOSE 5173
#npm run dev
CMD [ "npm","run", "dev" ] 
