FROM node:22-alpine

WORKDIR /app

# ย้ายมาโฟล์เดอร์ปัจจุบัน มี * เอาทุกอย่างที่มาจาก package.json
COPY package*.json ./

# run cmd
RUN npm install -g nodemon & npm install

# copy จาก ผู้ใช้ทางฝั่งซ้าย ไปยังฝั่งขวาคือ server 
COPY . .

# localhost server post 3000
EXPOSE 5000
#npm start
CMD [ "nodemon", "index.js" ] 
